### ISSUE TITLE
heat create failed in infra_host

### ISSUE THREAD

**Issue by mahsa-frj** [redhat-openstack/openshift-on-openstack#249] opened 2016-09-27 20:59 UTC
Hi everybody
heat execution crash after some minute, in the infra_host section, I get this error in the dashboard of openstack:

```
ClientException: resources.infra_host.resources.host: Unexpected API Error. Please report this at http: //bugs.launchpad.net/nova/ and attach the Nova API log if possible. <type 'exceptions.TypeError'> (HTTP 500) (Request-ID: req-2e92bdba-6ef4-4836-a675-134a96ccdfdd) 
```

thanks in advance.

**Comment by mahsa-frj** [comment] 2016-09-28 11:25
I try again and now one instance that name is my-openshift-infra.example.com was created, but after some minute heat execution crash and in infra_host section, I get below error in the dashboard:

```
Create Failed: WaitConditionTimeout: resources.infra_host.resources.wait_condition: 0 of 1 received 
```

thanks for your help.

**Comment by jprovaznik** [comment] 2016-09-29 06:41
Can you please check nova logs for errors? There should be more details about the reason in logfiles.

**Comment by mahsa-frj** [comment] 2016-10-02 13:20
@jprovaznik  my nova logs doesn't show any error. only in nova-consoleauth.log I saw this warning:

```
WARNING nova.consoleauth.manager [req-92ac9789-2a47-4ffc-88ef-2174b8d1b789 a590ae026ddd443e8592fe04382b39bd 0d0d200c019d477b904c3f01f9ac5529 - - -] Instance: d69e393e-de80-45ba-b34d-92696f43353c **failed to save into memcached**
```

**Comment by jprovaznik** [comment] 2016-10-03 10:26
can you please attach output of:
nova list
heat resource-list -n2 stackname
heat event-list -n2 stackname

**Comment by mahsa-frj** [comment] 2016-10-03 14:46
nova list:
[output1.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/506494/output1.txt)
heat resource-list -n2 my-openshift
[output2.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/506483/output2.txt)
heat event-list -n2 my-openshift
[output3.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/506481/output3.txt)

**Comment by jprovaznik** [comment] 2016-10-04 10:13
@mahsa-frj stack-creation timed out after 60 minutes (default timeout) - please check (or attach here) /var/log/cloud-init.log from bastion node to see what went wrong on the machine.

**Comment by mahsa-frj** [comment] 2016-10-04 11:38
thanks @jprovaznik . I attached the file. the end of the file, some error has appeared. 
[cloudinit.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/508326/cloudinit.txt)

**Comment by jprovaznik** [comment] 2016-10-04 11:48
so the problem is that there is a dependency issue - sshpass RPM seems to be missing when installing ansible on centos. Please check from which repo ansible is being installed and if sshpass is available somewhere (it might be an additional repo needs to be added maybe?).

**Comment by mahsa-frj** [comment] 2016-10-04 12:04
@jprovaznik ,  installation of ansible is being installed from **centos-openstack-liberty/x86_64** .
when I added epel-release repo with yum install epel-release and after that I execute yum -y install ansible-2.1.0.0-1.el7,  ansible with all dependencies (sshpass) was installed.
Now, how to continue to redeploy my heat?

**Comment by jprovaznik** [comment] 2016-10-04 12:11
Well, EPEL repo should be enabled automatically on CentOS. Are you sure your openshift-on-openstack is up-to-date? From cloudinit logfile it seems to me you don't have this commit included - https://github.com/redhat-openstack/openshift-on-openstack/commit/a10d8096316f653f7fc46213eca10e7d7ea6e227

If so, try on up-to-date OOO.

**Comment by mahsa-frj** [comment] 2016-10-05 07:19
@jprovaznik I updated OOO, and now I get **Create Failed: CREATE aborted**  in bastion_host section. 
I checked /var/log/cloud-init.log, the ansible package with dependencies installed successfully, and didn't show any error. 
please help me to understand what is my problem?

**Comment by jprovaznik** [comment] 2016-10-05 07:23
@mahsa-frj you need to attach at least output of:
heat event-list -n 2 stack
heat resource-list -n 2 stack

Which is bare minimum to at least start looking what is the problem.

**Comment by mahsa-frj** [comment] 2016-10-05 07:39
heat event-list -n 2 my_openshift1:
[output1.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/510301/output1.txt)
heat resource-list -n 2 my-openshift1:
[output2.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/510302/output2.txt)

**Comment by jprovaznik** [comment] 2016-10-05 07:49
It seems that it timed out waiting for finishing SW Deployment "| deployment_tune_ansible                                           | 9bebce30-6556-40da-a4c8-c13e680416fe | CREATE aborted". It seems os-collect-config on bastion node doesn't work as expected. Is you heat-api-cfn service up and running? If yes, what is content of /etc/os-collect-config.conf on your bastion host? Check os-collect-config in our debugging guide to do initial investigation:
https://github.com/redhat-openstack/openshift-on-openstack/blob/master/README_debugging.adoc#os-collect-config

**Comment by mahsa-frj** [comment] 2016-10-05 19:13
@jprovaznik thanks for your help.
I checked openstack services and heat-api-cfn not running. I enabled it and executed heat command again. 
now in **openshift_infra_nodes** section I get below output:

```
OverLimit: resources.openshift_infra_nodes.resources[0].resources.docker_volume:   VolumeLimitExceeded: Maximum number of volumes allowed (10) exceeded for quota 'volumes'.  (HTTP 413) (Request-ID: req-8c112ad8-2566-4c98-b97d-cb0a05da321d)
```

I have enough free space, but I don't know what is the source of problem. 
I attached some output:
heat event-list -n 2 my-openshift:
[output1.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/512101/output1.txt)
heat resource-list -n 2 my-openshift:
[output2.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/512102/output2.txt)
content of /etc/os-collect-config.conf:

```
[DEFAULT]
command = os-refresh-config
collectors = ec2
collectors = cfn
collectors = local

[cfn] 
metadata_url = http://172.22.33.8:8000/v1/
stack_name = my-openshift33-bastion_host-haqvgm6u5mvi
secret_access_key = 3041467d1f8b430293c299207e47cc6c
access_key_id = 92b5950009cb401bb85235d3a67a13a8
path = host.Metadata
```

**Comment by lebauce** [comment] 2016-10-06 10:00
@mahsa-frj This is an OpenStack quota issue. Trying raising up your "volumes" quota with :

```
cinder quota-update --volumes 1000 <YourTenantId>
```

or try removing existing volumes

**Comment by mahsa-frj** [comment] 2016-10-07 20:47
thanks @lebauce .
I tried again, and now 1 instance creates successfully, and 2 instances status are ERROR, I checked nova-conductor.log:

```
Failed to compute_task_build_instances: ServerGroup policy is not supported: ServerGroupAntiAffinityFilter not configured
```

and I checked nova.conf, the parameter ServerGroupAntiAffinityFilter wasn't set. should I set it? and If I set this parameter how to boot instances with this group while everything is automated with heat!

**Comment by mahsa-frj** [comment] 2016-10-08 10:53
@jprovaznik , I set ServerGroupAntiAffinityFilter in nova.conf and Now 4 instances was created successfully, but in the **openshift_nodes** section, I get this error:

```
Create Failed
Create Timed Out
```

I checked /var/log/cloud-init.log of my instances and doesn't see any error. 
I attached some output that you may need.
nova list:
[nova-list.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/517614/nova-list.txt)
heat event-list -n 2 my_openshift31:
[heat-event.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/517615/heat-event.txt)
heat resource-list -n 2 my_openshift31:
[heat-resource.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/517616/heat-resource.txt)

thanks in advanced

**Comment by jprovaznik** [comment] 2016-10-10 11:12
Yes, ServerGroupAntiAffinityFilter should be enabled (this default has changed in OSP 9 I think), from your logs it seems that creation timed out. It seems that running cloud-init on each node (bastion, master, node) takes 20 minutes, which is quite a lot - you can investigate in cloud-init log on each machine why it took so long and if you can improve this time. Otherwise you will need to increase creation timeout - here is a PR how to do it:
https://github.com/redhat-openstack/openshift-on-openstack/pull/264

**Comment by mahsa-frj** [comment] 2016-10-15 13:25
@jprovaznik I'll tried again and unfortunately stack creation failed in openshift node section.
and get below error:

```
create failed
OS::Heat::AutoScalingGroup
```

some output that you may need for helpnig me:
openshift_parameter.yaml:
[openshift_parameter.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/531148/openshift_parameter.txt)
nova list:
[nova-list.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/531145/nova-list.txt)
heat resource-list -n2 mu-openshift:
[heat-resource.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/531146/heat-resource.txt)
heat event-list -n2 my-openshift:
[heat-event.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/531147/heat-event.txt)

the output of my cloud-init.log in all the vm finish without any error.

thanks in advanced.

**Comment by mahsa-frj** [comment] 2016-10-16 13:54
Hi, I tried again, and now everything create successfully and pass autoscaling problem that refer in previous post. I stopped all ceilometer services.
BUT unfortunately in **cpu_alarm_high** section I get below error:

```
Resource Create Failed: Internalservererror: Resources.Cpu Alarm High: Internal Server Error (Http 500)
```

please help me to understand what is the source of issue?
thanks in advanced.

**Comment by jonjozwiak** [comment] 2016-10-17 12:33
@mahsa-frj - Did you mean to send the previous message about cpu_alarm_high to @jprovaznik?

**Comment by mahsa-frj** [comment] 2016-10-17 12:41
@jonjozwiak excuse me, I made a mistake.
I have an error in cpu_alarm_high section and couldn't solve it.

**Comment by jprovaznik** [comment] 2016-10-21 09:58
Sorry, I forgot about this issue. It's not a good idea to disable ceilometer server. accordign yo your event-list the reason seems to be that stack-create timed out (it took too long). It seems cloud-init on each node was extra slow (last host came up >hour after stack-create started), you can check cloud-init logs what took so long (this is really not common) or you can increase keystone token expiration time - https://github.com/redhat-openstack/openshift-on-openstack/blob/master/README_bugs.adoc#stack-creation-times-out

**Comment by mahsa-frj** [comment] 2016-10-22 12:36
thanks @jprovaznik  for your help.
I tried again, and I get below error:

```
Resource CREATE failed: Error:  resources.openshift_nodes.resources.hcz7lfnfczqu.resources.deployment_run_ansible: Deployment to   server failed: deploy_status_code: Deployment exited with non-zero status code: 1 
```

BUT when I use **heat stack-update** command, the stack_status is **UPDATE_COMPLETE**.
what does this mean? was the creation of heat successfully?

and when I use **oc** commands in master node, that command works.
but when I use oc get pos, I didn't get any output.
I create local docker-registery, but I get this output from docker logs:

```
--> Scaling docker-registry-1 to 1
error: couldn't scale docker-registry-1 to 1: User "system:serviceaccount:default:deployer" cannot watch   replicationcontrollers in project "default"
--> Error listing events for replication controller docker-registry-1: User   "system:serviceaccount:default:deployer" cannot list events in project "default"
```

please help me to understand what is my problem?
thanks in advanced

**Comment by jprovaznik** [comment] 2016-10-24 06:47
Hi,
the "Resource CREATE failed: Error:...." is not sufficient information to determine the reason of failure (steps to get more info are in previous comments).

> BUT when I use heat stack-update command, the stack_status is UPDATE_COMPLETE.
> ^ Probably because stack-create timed out (at least it was your problem last time - see ma last comment), then stack-update just finished the stack completion. Did you bump the timeouts as suggested last time?

I haven't seen the registry issue above, if you re-recreate registry manually does it work?

**Comment by mahsa-frj** [comment] 2016-10-24 07:33
thanks for your reply, @jprovaznik .
yes I increased keystone token timeout when you said me.
I have one question, the docker registry and router in my installation, didn't create automatically and I should create it manually and when I create it manually doesn't work properly. 
Is it correct to create it manually or heat create them automatically?
one of the volumes that name is my-openshift-2-registry_volume-tytevypljrlr-volume-vxjyhqn2tdfq doesn't attach to any instances...!

**Comment by jprovaznik** [comment] 2016-10-31 08:24
Router/registry deployment is optional - it's deployed if you pass deploy_router=true and deploy_registry=true (for registry don't forget to pass also openstack vars - https://github.com/redhat-openstack/openshift-on-openstack/blob/v0.9.5/openshift.yaml#L283)

**Comment by jprovaznik** [comment] 2016-10-31 08:26
Closing this one - this became quite off-topic (regarding the original Issue report) if there are other issues, open a new proper issue for it.

**Closed as completed by jprovaznik** 2016-10-31 08:26 UTC
