### ISSUE TITLE
heat create fails; ERROR: cannot find role in /var/lib/ansible/playbooks/roles/openshift_router

### ISSUE THREAD

**Issue by rawlingsj** [redhat-openstack/openshift-on-openstack#92] opened 2016-04-19 09:47 UTC
openshift ansible fails with..

```
[root@my_openshift5-infra centos]# cat /var/log/ansible.28990
ERROR: cannot find role in /var/lib/ansible/playbooks/roles/openshift_router or /var/lib/ansible/playbooks/openshift_router or /usr/share/ansible/openshift-ansible/roles/openshift_router
```

Not sure if this is openshift-ansible or openshift-on-openstack yet but I've done a bit of googling and nothing comes up so I'm thinking it might be best to raise here first

**Comment by jprovaznik** [comment] 2016-04-19 10:12
This is probably duplicate of https://github.com/redhat-openstack/openshift-on-openstack/issues/84. if you are using deploy_router=true, then removing this param should fix it

**Closed as completed by jprovaznik** 2016-04-19 10:12 UTC
