### ISSUE TITLE
Failure traced to python error in ansible facts.py

### ISSUE THREAD

**Issue by dkranz** [redhat-openstack/openshift-on-openstack#210] opened 2016-08-31 14:37 UTC
I was running the playbooks (1 master, 1 node). The master succeeded but node failed with this error from the ansible log on the infra node. Seems there is a path where 'seconds' is referenced but has never been set in this code https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts.py#L123

I have no idea what caused this path to execute.

TASK [openshift_facts : Gather Cluster facts and set is_containerized if needed] ***
task path: /usr/share/ansible/openshift-ansible/roles/openshift_facts/tasks/main.yml:26
Using module file /usr/share/ansible/openshift-ansible/roles/openshift_facts/library/openshift_facts.py
<localhost> ESTABLISH SSH CONNECTION FOR USER: cloud-user
<localhost> SSH: EXEC ssh -vvv -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/%h-%r localhost '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-rojdmbqiupevmxxhhamyevxexpdffnbd; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "openshift_facts"
    }, 
    "module_stderr": "OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 6427\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nTraceback (most recent call last):\n  File \"/tmp/ansible_51iSII/ansible_module_openshift_facts.py\", line 2168, in <module>\n    main()\n  File \"/tmp/ansible_51iSII/ansible_module_openshift_facts.py\", line 2149, in main\n    protected_facts_to_overwrite)\n  File \"/tmp/ansible_51iSII/ansible_module_openshift_facts.py\", line 1620, in **init**\n    self.system_facts = ansible_facts(module, ['hardware', 'network', 'virtual', 'facter'])\n  File \"/tmp/ansible_51iSII/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3257, in ansible_facts\n  File \"/tmp/ansible_51iSII/ansible_modlib.zip/ansible/module_utils/facts.py\", line 1002, in populate\n  File \"/tmp/ansible_51iSII/ansible_modlib.zip/ansible/module_utils/facts.py\", line 132, in wrapper\nUnboundLocalError: local variable 'seconds' referenced before assignment\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "parsed": false

**Comment by lebauce** [comment] 2016-09-01 13:13
Nice catch.

That's definitely a bug, I suggest you file an issue on the Ansible Github page.

**Comment by dkranz** [comment] 2016-09-01 13:35
There already was one: https://github.com/openshift/openshift-ansible/issues/2247

**Comment by jprovaznik** [comment] 2016-09-02 08:32
Hi David, I think it is caused by using the old openshift_ansible_git_rev in your env file, could you please check again when using openshift-ansible from RPM (on rhel) or referring master branch (on centos)?

**Comment by jprovaznik** [comment] 2016-09-05 10:21
Closing this, AFAIK removing the old git_rev solved the issue for you, reopen if the problem occurs.

**Closed as completed by jprovaznik** 2016-09-05 10:21 UTC
