### ISSUE TITLE
Heat Templates can not be Provisioned using the UI

### ISSUE THREAD

**Issue by sferich888** [redhat-openstack/openshift-on-openstack#73] opened 2016-04-05 13:51 UTC
Changes to the templates need to be made so that, each "resource" or type can be referenced by "name" and as such environment files can be supplied, that point to the resources by file (for console deployments), or with in the UI (by using URL locations). 

More on this can be seen in http://docs.openstack.org/developer/heat/template_guide/environment.html

**Comment by jprovaznik** [comment] 2016-04-06 07:42
To sum up the problem: we use HOT syntax in heat templates and refer to other files from the top-level openshift.yaml template. Other files are referenced by _relative path_ for obvious reasons (to make sure templates will work no matter where are placed). When a user tries to create a heat stack from Horizon UI, it fails with these templates, in heat-engine log you can find errors like this:
2016-04-06 03:14:45.170 30446 INFO heat.common.urlfetch [req-84300e0b-7f77-4015-87cd-85216e2ce75e db21571aa36742638d003697bdd902b7 8f1373acd2cc481a916fc809f6c63524] Fetching data from infra
.yaml
2016-04-06 03:14:45.170 30446 DEBUG oslo_messaging.rpc.dispatcher [req-84300e0b-7f77-4015-87cd-85216e2ce75e db21571aa36742638d003697bdd902b7 8f1373acd2cc481a916fc809f6c63524] Expected exception during message handling (Could not fetch remote template "infra.yaml": Invalid URL scheme ) _dispatch_and_reply /usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py:145

AIUI the problem is that Horizon can not deal with relative path references properly. This bug describes the same situation:
https://bugs.launchpad.net/python-heatclient/+bug/1467781

IOW the issue has to be fixed on Horizon side.

**Comment by sferich888** [comment] 2016-04-06 11:02
I don't feel that bug is relevant to the request I am making. What I am suggesting is that you provide 2 files a local resource registry and a remote resource registry. When you use the ue the remote resource registry is used and points or URL based files. 

When the local is used it points to relative files paths and is used on the command line.

**Comment by jprovaznik** [comment] 2016-04-06 11:51
Re relevancy: what you are describing is a workaround for the bug I linked above - when Horizon fixes loading of referenced files you just pass top-level template URL. The same works in CLI, .e.g:
heat stack-create oshift2 -e ~/openshift-on-openstack/env_origin.yaml -f http://with_openshift_templates/templates/openshift.yaml

And once Horizon starts using "process_multiple_environments_and_files" method, it will work there too and none of this should be needed.

If I understand your proposal you are suggesting we should maintain an extra set of resource overrides for each referenced file, this override would be _absolute_ URL pointing to this github repo. So this couldn't be used anyway in real life because there is often need to tune templates according you your needs, and extra pain for anyone trying to re-use these templates and keep them consistent.

**Closed as not planned** 2023-04-03 17:55 UTC
